---
- name: Disable swap immediately
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Remove swap entries from /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#\s].*\s+swap\s+.*)$'
    replace: '# \1'