---
all:
  vars:
    ansible_user: r16a
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3

  children:
    proxmox:
      # Physical servers with proxmox
      hosts:
        r16a-svr-00:
          ansible_host: 192.168.1.100
        r16a-svr-01:
          ansible_host: 192.168.1.102
      vars:
        ansible_user: root

    k8s_control_plane:
      hosts:
        # Control plane on svr-00
        control-plane-00:
          ansible_host: 192.168.1.120
        # Control plane on svr-01  
        control-plane-01:
          ansible_host: 192.168.1.123

    k8s_workers:
      hosts:
        # Work nodes on control-plane-00
        work-node-00:
          ansible_host: 192.168.1.121
        work-node-01:
          ansible_host: 192.168.1.122
        # Work nodes on control-plane-01  
        work-node-02:
          ansible_host: 192.168.1.124
        work-node-03:
          ansible_host: 192.168.1.125

    k8s:
      children:
        k8s_control_plane:
        k8s_workers:

    nfs:
      hosts:
        storage-00:
          ansible_host: 192.168.1.110